test: Add unit tests
CUTR-at-USF/gnss-ride-hailing-analyzer pull request #7
Opened 2021-02-26 23:22 UTC by BumbleFlash

This PR adds unit-tests to the project. 

Tasks:- 
- [ ] Create test source folder and test class (under `src/test/...`) 
- [x] Move files to `src/test/resources/`
- [ ] assert that each element in the returned List matches what is expected based on the file

2021-02-27 15:19 UTC, BumbleFlash commented
@barbeau I believe that the current test implementation takes data from the `src/resources` instead of `test/resources`. This is probably because we are calling the `getReader()` inside the parser. One solution here is to pass the reader as a function argument to the `parseFile` function. Thoughts?

2021-03-01 19:58 UTC, barbeau reviewed
>I believe that the current test implementation takes data from the src/resources instead of test/resources. This is probably because we are calling the getReader() inside the parser. One solution here is to pass the reader as a function argument to the parseFile function. Thoughts?

If I delete everything under src/main/resources, the tests still pass for me. So seems like it works?

Code LGTM, so if everything seems to be working without the resources under main if you delete those files then I believe this PR should be good to merge.

2021-03-01 19:58 UTC, barbeau commented on src/main/resources/Transportation_Network_Providers_reduced_records.csv
> +﻿TripID,TripStartTimestamp,TripEndTimestamp,TripSeconds,TripMiles,PickupCensusTract,DropoffCensusTract,PickupCommunityArea,DropoffCommunityArea,Fare,Tip,AdditionalCharges,TripTotal,SharedTripAuthoriz
Current records in main/resources should be removed - we don't want to bundle them in the JAR.

2021-03-01 20:02 UTC, barbeau commented
Actually, one other item - could you please double-check that after delete the files from resources folder you're still able to parse them from running the main class by passing in their paths?

If I try running `ProcessorMain` with the command-line parameters `"src/test/resources/gnss_log_2021_02_05_13_20_58_beans.txt" "src/test/resources/Transportation_Network_Providers_reduced_records.csv"` (with or without the quotes) I get this error:

```
Exception in thread "main" com.univocity.parsers.common.TextParsingException: java.lang.NullPointerException - null
Parser Configuration: CsvParserSettings:
	Auto configuration enabled=true
	Auto-closing enabled=true
	Autodetect column delimiter=false
	Autodetect quotes=false
	Column reordering enabled=true
	Delimiters for detection=null
	Empty value=null
	Escape unquoted values=false
	Header extraction enabled=true
	Headers=null
	Ignore leading whitespaces=true
	Ignore leading whitespaces in quotes=false
	Ignore trailing whitespaces=true
	Ignore trailing whitespaces in quotes=false
	Input buffer size=1048576
	Input reading on separate thread=true
	Keep escape sequences=false
	Keep quotes=false
	Length of content displayed on error=-1
	Line separator detection enabled=false
	Maximum number of characters per column=4096
	Maximum number of columns=512
	Normalize escaped line separators=true
	Null value=null
	Number of records to read=all
	Processor=com.univocity.parsers.common.processor.ConcurrentRowProcessor
	Restricting data in exceptions=false
	RowProcessor error handler=null
	Selected fields=none
	Skip bits as whitespace=true
	Skip empty lines=true
	Unescaped quote handling=nullFormat configuration:
	CsvFormat:
		Comment character=#
		Field delimiter=,
		Line separator (normalized)=\n
		Line separator sequence=\n
		Quote character="
		Quote escape character="
		Quote escape escape character=null
Internal state when error was thrown: line=0, column=0, record=0
	at com.univocity.parsers.common.AbstractParser.handleException(AbstractParser.java:402)
	at com.univocity.parsers.common.AbstractParser.beginParsing(AbstractParser.java:277)
	at com.univocity.parsers.common.AbstractParser.parse(AbstractParser.java:128)
	at edu.usf.cutr.grha.io.GPSTestParser.parseFile(GPSTestParser.java:45)
	at edu.usf.cutr.grha.ProcessorMain.main(ProcessorMain.java:33)
Caused by: java.lang.NullPointerException
	at com.univocity.parsers.common.input.concurrent.ConcurrentCharLoader.stopReading(ConcurrentCharLoader.java:178)
	at com.univocity.parsers.common.input.concurrent.ConcurrentCharLoader.nextBucket(ConcurrentCharLoader.java:141)
	at com.univocity.parsers.common.input.concurrent.ConcurrentCharInputReader.reloadBuffer(ConcurrentCharInputReader.java:111)
	at com.univocity.parsers.common.input.AbstractCharInputReader.updateBuffer(AbstractCharInputReader.java:203)
	at com.univocity.parsers.common.input.AbstractCharInputReader.start(AbstractCharInputReader.java:179)
	at com.univocity.parsers.common.input.AbstractCharInputReader.start(AbstractCharInputReader.java:189)
	at com.univocity.parsers.common.AbstractParser.beginParsing(AbstractParser.java:275)
	... 3 more
```

2021-03-01 23:04 UTC, barbeau commented
@BumbleFlash Pointed out that we need to update the `getReader()` method to load from a file instead of resources. A good project to model on best practice for loading a file is the GTFS validator:
https://github.com/MobilityData/gtfs-validator/blob/b9ce3a4abaf2c7fb52438ef6d05a394c730dd3ae/main/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java#L81

2021-03-02 01:56 UTC, BumbleFlash commented
@barbeau The program will now accept the path to the file as a command-line argument. It can be an absolute and relative path.

2021-03-02 23:15 UTC, barbeau requested changes
Thanks @BumbleFlash! Some comments in-line.

2021-03-02 23:15 UTC, barbeau commented on src/main/java/edu/usf/cutr/grha/io/CsvParser.java
> +public class CsvParser {
With these changes it doesn't make sense to me to have a common base class that is extended to implement the other parser classes. The methods here are simple single line methods that could be implemented directly in the other classes, either the parsers or the main method or a utility class (in the main class you're currently treating these as if they were utility methods) - let's get rid of this class.

2021-03-02 23:15 UTC, barbeau commented on src/main/java/edu/usf/cutr/grha/ProcessorMain.java
> +    public static void main(String[] args) throws FileNotFoundException {
Instead of throwing `FileNotFoundException`, you should catch it and print out a message to the user that the file they specified can't be found.

2021-03-02 23:15 UTC, barbeau commented on src/main/java/edu/usf/cutr/grha/ProcessorMain.java
> +        InputStream inputStream0 = new CsvParser().getInputStream(args[0]);
The base class `CsvParser` shouldn't be instantiated here - you're using it more like a utility method, and in that case the code should be moved to a utility class.

2021-03-02 23:15 UTC, barbeau commented on src/test/java/edu/usf/cutr/grha/test/ChicagoTncDataTest.kt
> +    private val chicagoDataFile = "src/test/resources/Transportation_Network_Providers_reduced_records.csv"
If these files are on in the resources forlder, they should really be accessed with `classLoader.getResourceAsStream(fileName);`. You could open an input stream this way and then pass that to the parsers.

2021-03-03 00:35 UTC, BumbleFlash commented
@barbeau After I removed the code from the `CsvParser.java`, I realized the parser code is the same and the online difference being the model class. So I created another `parseFile` function that returns a generic type `List<T>`, satisfying both the parsers. Thoughts?

2021-03-03 16:31 UTC, barbeau reviewed
@BumbleFlash This is looking good! A few more comments in-line.

2021-03-03 16:31 UTC, barbeau commented on src/main/java/edu/usf/cutr/grha/ProcessorMain.java
> +            GPSTestParser gpsTestParser = new GPSTestParser(gps_input_stream);
You could chain the above three lines into:

```java
GPSTestParser gpsTestParser = new GPSTestParser(new FileInputStream(new File(args[0])));
```

Same for other parsers

2021-03-03 16:31 UTC, barbeau commented on src/main/java/edu/usf/cutr/grha/io/CsvParser.java
> +    public <T> List<T> parseFile(BeanListProcessor<T> beanListProcessor, InputStream inputStream) {
Good job finding common implementation to share here! It makes sense to keep CsvParser then.

2021-03-03 16:31 UTC, barbeau commented on src/main/java/edu/usf/cutr/grha/io/GPSTestExtendedHeaderParser.java
>  public class GPSTestExtendedHeaderParser extends CsvParser {
If this class doesn't use anything in CsvParser, it shouldn't extend it.

2021-03-03 16:31 UTC, barbeau commented on src/main/java/edu/usf/cutr/grha/io/GPSTestExtendedHeaderParser.java
> +        List<String[]> allRows = csvParser.parseAll(reader);
Similarly, I'd collapse the above two lines into one.

2021-03-04 16:07 UTC, barbeau approved these changes
👍  Thanks @BumbleFlash!

2021-03-04 16:07 UTC, merged